const fs=require('fs');
const path=require('path');
const root=__dirname;
const launcher=fs.readFileSync(path.join(root,'club-pulse.js'),'utf8');
const policy=fs.readFileSync(path.join(root,'club-pulse-data-policy-patch.js'),'utf8');
let failed=0;
const check=(n,ok)=>{if(ok)console.log(`✓ ${n}`);else{console.error(`✗ ${n}`);failed++}};
const has=(s,x)=>s.includes(x);
try{new Function(`return (async()=>{\n${policy}\n})`);check('data policy syntax',true)}catch(e){console.error(e.message);check('data policy syntax',false)}
check('launcher pins data policy v8',has(launcher,'fa0b30efd1407e4221175b25da282b904c713b71')&&has(launcher,'ClubPulseDataPolicyPatch_v8.js')&&has(launcher,"'data-policy8'"));
check('data policy loads after resilience',has(launcher,"+q+'\\n'+r+'\\n'+dp"));
check('adaptive refresh tiers exist',['3*60*1000','5*60*1000','15*60*1000','30*60*1000','60*60*1000'].every(x=>has(policy,x)));
check('standings cache is league-shared',has(policy,"standings_${String(club.comp||'league').toLowerCase()}.json")&&has(policy,'CP_DP_STANDINGS_TTL=30*60*1000'));
check('supplemental next cache is twelve hours',has(policy,'CP_DP_NEXT_OVERLAY_TTL=12*60*60*1000'));
check('live quota reserve ceiling is forty',has(policy,'CP_DP_NEXT_QUOTA_CEILING=40'));
check('quota conservation skips supplemental next',has(policy,'cpDpQuotaCount()>=CP_DP_NEXT_QUOTA_CEILING')&&has(policy,"nextProvider:d.nextProvider||'quota-conserve'"));
check('global live cache is three minutes',has(policy,'CP_DP_GLOBAL_LIVE_TTL=3*60*1000')&&has(policy,"path('live_global.json')"));
check('global live endpoint is shared',has(policy,"liveApi('/fixtures?live=all',token)")&&has(policy,"liveProvider:'apiFootball-global'"));
check('global live lookup prefers canonical team name before id fallback',has(policy,'function cpDpFindLiveByName')&&has(policy,'resolveLiveTeamId(token)'));
check('future FINISHED rows are reclassified before mapping',has(policy,"m?.status!=='FINISHED'")&&has(policy,"status:'SCHEDULED'")&&has(policy,'cpDpTemporalizeMatches(matches)'));
check('future cached POST is neutralized into NEXT',has(policy,"d.mode==='POST'&&d.recentResult?.utcDate")&&has(policy,'t>Date.now()')&&has(policy,"futureResultCorrected:true")&&has(policy,'recentResult:null'));
check('home-screen simulated match modes are suppressed',has(policy,"CP_DP_SIMULATED_MATCH_MODES=['live','post','cl','fa','efl']")&&has(policy,'!config.runsInApp&&CP_DP_SIMULATED_MATCH_MODES.includes(mode)')&&has(policy,'qaModeSuppressed'));
check('in-app simulation still delegates to core',has(policy,'return CP_DP_BASE_APPLY_TEST_MODE(d)'));
check('expired stale LIVE is neutralized',has(policy,"d.mode==='LIVE'")&&has(policy,"kickoff+4*60*60*1000")&&has(policy,"ourScore:null,opponentScore:null")&&has(policy,"liveExpired:true"));
check('expired stale POST yields next fixture',has(policy,"d.mode==='POST'")&&has(policy,"postExpired:true")&&has(policy,"typeof POST==='number'?POST:10*60*60*1000"));
check('readonly core updated binding is never reassigned',!/(^|[^A-Za-z0-9_$])updated\s*=/.test(policy)&&!has(policy,'CP_DP_BASE_UPDATED=updated'));
check('forced outage remains delegated to resilience',has(policy,'return cpDpSanitizeStale(await CP_DP_BASE_LOAD_DATA(t))')&&has(policy,'return CP_DP_BASE_LIVE_OVERLAY(d)'));
check('small stale-next parity guard exists',has(policy,'CP_DP_BASE_BUILD_MATCH_SMALL=buildMatchSmall')&&has(policy,"mode:'STALE_NEXT'")&&has(policy,"return'更新待ち'")&&has(policy,"return'VS'"));
if(failed){console.error(`\nData policy contract QA FAILED: ${failed}`);process.exit(1)}
console.log('\nClub Pulse data policy contract QA PASSED');
