const fs=require('fs');
const path=require('path');
const r=n=>fs.readFileSync(path.join(__dirname,n),'utf8');
const core=r('club-pulse-core.js');
const themes=r('club-pulse-theme-registry-patch.js');
const resilience=r('club-pulse-resilience-patch.js');
const policy=r('club-pulse-data-policy-patch.js');
const small=r('club-pulse-small-presentation-patch.js');
let failed=0;
const check=(n,ok)=>{if(ok)console.log(`✓ ${n}`);else{console.error(`✗ ${n}`);failed++}};
check('core retains small builder',core.includes('function buildSmall'));
check('theme system keeps shared small builder shell',themes.includes('buildSmall=function')&&themes.includes('w.refreshAfterDate=new Date(Date.now()+refreshDelay(d))'));
check('resilience keeps stale saved-data semantics',resilience.includes("text(s,'保存',6.2")&&resilience.includes('t.headerAccent||shellText'));
check('data policy keeps stale post-kickoff semantics',policy.includes("mode:'STALE_NEXT'")&&policy.includes("return'更新待ち'")&&policy.includes("return'VS'"));
check('small presentation owns final header match footer',small.includes('buildHeaderSmall=function')&&small.includes('buildMatchSmall=function')&&small.includes('buildFooterSmall=function'));
check('small presentation defines adaptive hierarchy',small.includes('const CP_SP_TYPO=')&&small.includes('team:9.8')&&small.includes('meta:8.7')&&small.includes('footer:7.6'));
check('short Japanese names stay full size policy',small.includes('const CP_SP_FULL_NAME_LIMIT=6')&&small.includes('const CP_SP_SOFT_NAME_LIMIT=9'));
check('curated long-name labels beat generic aliases',small.includes('const CP_SP_PREFERRED_LABELS=')&&small.indexOf('if(CP_SP_PREFERRED_LABELS[n])return CP_SP_PREFERRED_LABELS[n]')<small.indexOf('if(CP_SP_SMALL_ALIASES[n])return CP_SP_SMALL_ALIASES[n]'));
check('supported long clubs use readable natural labels',small.includes("'レヴァークーゼン':'Leverkusen'")&&small.includes("'フランクフルト':'Frankfurt'")&&small.includes("'シュトゥットガルト':'Stuttgart'")&&small.includes("'フィオレンティーナ':'Fiorentina'")&&small.includes("'フェイエノールト':'Feyenoord'"));
check('natural Japanese semantic labels are preserved',small.includes("'レアル・ソシエダ':'ソシエダ'")&&small.includes("'アストン・ヴィラ':'ヴィラ'"));
check('latin labels get width-aware typography',small.includes('function cpSpLatinLabel(label)')&&small.includes('if(n<=8)return 8.7')&&small.includes('if(n<=10)return 8.2'));
check('semantic aliases remain available for genuinely long labels',small.includes("'ノッティンガム・フォレスト':'フォレスト'")&&small.includes("'アスレティック・ビルバオ':'ビルバオ'")&&small.includes("'ボルシア・ドルトムント':'ドルトムント'"));
check('generic team labels enforce readability floor',small.includes('teamMinScale:.70')&&small.includes('nm.minimumScaleFactor=CP_SP_TYPO.teamMinScale'));
check('generic team labels stay single-line clipping safe',small.includes('nm.lineLimit=1'));
check('generic team labels honor cardText token',small.includes('heavy(name,label,opt.nameSize||cpSpTeamFont(label),cpSpCardColor())')&&small.includes("return t?.cardText||t?.text||'#F8FAFC'"));
check('unknown long names can fall back to provider short code',small.includes("/^[A-Z0-9.-]{2,5}$/i.test(fb)"));
check('NEXT and scored states use separate row geometry',small.includes('teamWidthNext:55')&&small.includes('teamWidthScore:48')&&small.includes('scoreWidthNext:32')&&small.includes('scoreWidthScore:42')&&small.includes('function cpSpRowMetrics(mode)'));
check('NEXT VS column remains protected',small.includes('scoreWidthNext:32')&&small.includes('scoreNext:14.0'));
check('scored state width stays protected',small.includes("const scored=mode==='LIVE'||mode==='POST'")&&small.includes('scoreWidth:CP_SP_TYPO.scoreWidthScore'));
check('LIVE POST numeric scores bypass inherited ellipsis risk',small.includes('function cpSpScoreValue')&&small.includes('Number.isFinite(m?.ourScore)')&&small.includes('`${m.ourScore}-${m.opponentScore}`'));
check('score renderer uses dynamic width and single-line scaling',small.includes('sb.size=new Size(gm.scoreWidth,22)')&&small.includes('scoreMinScale:.72')&&small.includes('sc.lineLimit=1'));
check('special Real and Barcelona crest treatment is preserved',small.includes("t?.key==='realmadrid'")&&small.includes('cpRealTeamBlock')&&small.includes("t?.key==='barcelona'")&&small.includes('cpBarcelonaTeamBlock'));
check('NEXT LIVE POST and stale-next share final small renderer',small.includes("view.mode==='LIVE'")&&small.includes("view.mode==='POST'")&&small.includes("d?.mode==='STALE_NEXT'")&&small.includes("mode:'STALE_NEXT'"));
check('Dortmund shell header stays on headerAccent',small.includes('t?.headerAccent||CP_DESIGN_TOKENS?.shell?.text'));
if(failed){console.error(`\nSmall widget contract QA FAILED: ${failed}`);process.exit(1)}
console.log('\nClub Pulse canonical Small Presentation System v11 QA PASSED');