const fs=require('fs');
const path=require('path');
const r=n=>fs.readFileSync(path.join(__dirname,n),'utf8');
const core=r('club-pulse-core.js');
const themes=r('club-pulse-theme-registry-patch.js');
const resilience=r('club-pulse-resilience-patch.js');
const policy=r('club-pulse-data-policy-patch.js');
const small=r('club-pulse-small-presentation-patch.js');
let failed=0;
const check=(n,ok)=>{if(ok)console.log(`✓ ${n}`);else{console.error(`✗ ${n}`);failed++}};
check('core retains small builder',core.includes('function buildSmall'));
check('theme system keeps shared small builder shell',themes.includes('buildSmall=function')&&themes.includes('w.refreshAfterDate=new Date(Date.now()+refreshDelay(d))'));
check('resilience keeps stale saved-data semantics',resilience.includes("text(s,'保存',6.2")&&resilience.includes('t.headerAccent||shellText'));
check('data policy keeps stale post-kickoff semantics',policy.includes("mode:'STALE_NEXT'")&&policy.includes("return'更新待ち'")&&policy.includes("return'VS'"));
check('small presentation owns final header match footer',small.includes('buildHeaderSmall=function')&&small.includes('buildMatchSmall=function')&&small.includes('buildFooterSmall=function'));
check('small presentation defines adaptive hierarchy',small.includes('const CP_SP_TYPO=')&&small.includes('team:9.8')&&small.includes('meta:8.7')&&small.includes('footer:7.6'));
check('length-aware team font exists',small.includes('function cpSpTeamFont(label)')&&small.includes('if(n===5)return 8.9')&&small.includes('return 8.4'));
check('five to six character names remain canonical',small.includes('if(Array.from(n).length<=6)return n'));
check('generic team labels enforce readability scale floor',small.includes('teamMinScale:.82')&&small.includes('nm.minimumScaleFactor=CP_SP_TYPO.teamMinScale'));
check('generic team labels stay single-line clipping safe',small.includes('nm.lineLimit=1')&&small.includes('teamWidth:54'));
check('generic team labels honor cardText token',small.includes('cpSpTeamFont(label)')&&small.includes("return t?.cardText||t?.text||'#F8FAFC'"));
check('cut-looking aliases are replaced with semantic labels',small.includes("'ホッフェンハイム':'TSG'")&&small.includes("'フィオレンティーナ':'ヴィオラ'")&&small.includes("'シュトゥットガルト':'VfB'"));
check('unknown long names can fall back to provider short code',small.includes("/^[A-Z0-9.-]{2,5}$/i.test(fb)"));
check('all small teams share rebalanced canonical geometry',small.includes('teamWidth:54')&&small.includes('scoreWidth:32')&&small.includes('logo:40'));
check('center score column stays clipping-safe after rebalance',small.includes('scoreWidth:32')&&small.includes('scoreMinScale:.76')&&small.includes('sb.size=new Size(CP_SP_TYPO.scoreWidth,22)'));
check('LIVE POST numeric scores bypass inherited ellipsis risk',small.includes('function cpSpScoreValue')&&small.includes('Number.isFinite(m?.ourScore)')&&small.includes('`${m.ourScore}-${m.opponentScore}`'));
check('special Real and Barcelona crest treatment is preserved',small.includes("t?.key==='realmadrid'")&&small.includes('cpRealTeamBlock')&&small.includes("t?.key==='barcelona'")&&small.includes('cpBarcelonaTeamBlock'));
check('NEXT LIVE POST and stale-next share final small renderer',small.includes("view.mode==='LIVE'")&&small.includes("view.mode==='POST'")&&small.includes("d?.mode==='STALE_NEXT'")&&small.includes("mode:'STALE_NEXT'"));
check('Dortmund shell header stays on headerAccent',small.includes('t?.headerAccent||CP_DESIGN_TOKENS?.shell?.text'));
if(failed){console.error(`\nSmall widget contract QA FAILED: ${failed}`);process.exit(1)}
console.log('\nClub Pulse canonical Small Presentation System v7 QA PASSED');