const fs=require('fs');
const path=require('path');
const src=fs.readFileSync(path.join(__dirname,'club-pulse.js'),'utf8');
let failed=0;
function check(name,ok){if(ok)console.log(`✓ ${name}`);else{console.error(`✗ ${name}`);failed++}}
check('launcher pins core to immutable commit',src.includes('30a2b7f1b5c58d4ffa7e91047b637692c3cac7ce/scriptable/club-pulse-core.js'));
check('launcher uses core v2 local cache',src.includes('ClubPulseCore_v2.js')&&src.includes("CORE+'?v=core2'"));
check('launcher uses resilience v6 local cache',src.includes('ClubPulseResiliencePatch_v6.js'));
check('launcher fetch tag is resilience6',src.includes("'resilience6'"));
check('launcher pins resilience v6 commit',src.includes('968fd0308afd6ea0998d8317357d86af9d8aa0c3'));
check('launcher uses data policy v8 local cache',src.includes('ClubPulseDataPolicyPatch_v8.js'));
check('launcher fetch tag is data-policy8',src.includes("'data-policy8'"));
check('launcher pins data policy v8 commit',src.includes('fa0b30efd1407e4221175b25da282b904c713b71'));
check('launcher uses premium visual v6 local cache',src.includes('ClubPulsePremiumVisualPatch_v6.js'));
check('launcher fetch tag is premium6',src.includes("'premium6'"));
check('launcher pins premium visual v6 commit',src.includes('ecc546bf6f1bfb3d82e7a601d07622b3d716dcba/scriptable/club-pulse-premium-visual-patch.js'));
check('launcher uses small presentation v11 local cache',src.includes('ClubPulseSmallPresentationPatch_v11.js'));
check('launcher fetch tag is small-presentation11',src.includes("'small-presentation11'"));
check('launcher pins small presentation v11 commit',src.includes('0191f8450c4ca7c3c8277da2223cdf5c6bb0f15b/scriptable/club-pulse-small-presentation-patch.js'));
check('launcher uses canonical form system v1',src.includes('ClubPulseFormSystemPatch_v1.js')&&src.includes("'form-system1'"));
check('launcher pins canonical form system v1',src.includes('41ce4238ea15fb7dc8eb668011c98e203acd1aa4/scriptable/club-pulse-form-system-patch.js'));
check('launcher uses wave2 clubs and themes v5',src.includes('ClubPulseWave2ClubsPatch_v1.js')&&src.includes("'wave2-clubs1'")&&src.includes('ClubPulseWave2ThemesPatch_v5.js')&&src.includes("'wave2-themes5'"));
check('launcher pins wave2 immutable commits',src.includes('c53a62e6308fb99d6605d9b6c8d960869140dd46/scriptable/club-pulse-wave2-clubs-patch.js')&&src.includes('5e6abb10e817d5dbebd0f2b95d9e8106da8ff401/scriptable/club-pulse-wave2-themes-patch.js'));
check('launcher uses wave3 Netherlands v2 cache',src.includes('ClubPulseWave3NetherlandsClubsPatch_v1.js')&&src.includes("'wave3-nl-clubs1'")&&src.includes('ClubPulseWave3NetherlandsPatch_v2.js')&&src.includes("'wave3-netherlands2'"));
check('launcher pins wave3 venue-audited immutable commit',src.includes('b6b1e42237d899fc3084ced49a1974185c5b43e3/scriptable/club-pulse-wave3-netherlands-clubs-patch.js')&&src.includes('4b81db83ea2ef39b2ae171b40649f85c439d04e7/scriptable/club-pulse-wave3-netherlands-patch.js'));
check('launcher uses wave4 Lens v1 caches',src.includes('ClubPulseWave4LensClubPatch_v1.js')&&src.includes("'wave4-lens-club1'")&&src.includes('ClubPulseWave4LensPatch_v1.js')&&src.includes("'wave4-lens1'"));
check('launcher pins wave4 Lens immutable commits',src.includes('28a95c8d790e4a15a9204ff45694d5dde361600e/scriptable/club-pulse-wave4-lens-club-patch.js')&&src.includes('6380251307413da618226363e5f22800df9301dc/scriptable/club-pulse-wave4-lens-patch.js'));
check('wave4 registry injects before core parameter resolution',src.includes("c=c.slice(0,pk)+cr+'\\n'+ec+'\\n'+w2c+'\\n'+w3c+'\\n'+w4c+'\\n'+c.slice(pk)"));
check('canonical form system runs last',src.includes("+w4l+'\\n'+fs"));
check('patch loader remains local-first',src.includes("if(F.fileExists(file)){let s=F.readString(file);if(s&&s.length>=min)return s}"));
check('launcher documents 44-club architecture',src.includes('Club Pulse 44-club runtime')&&src.includes('Wave 4 adds RC Lens')&&src.includes('Data Policy v8')&&src.includes('Premium Visual v6')&&src.includes('Small Presentation v11')&&src.includes('Wave 2 Theme v5')&&src.includes('Wave 3 Netherlands v2')&&src.includes('Canonical Form System v1'));
if(failed){console.error(`\nLauncher version QA FAILED: ${failed}`);process.exit(1)}
console.log('\nClub Pulse 44-club launcher version QA PASSED');
